/*
 * generated by Xtext 2.17.1
 */
package org.ripacola.lang


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class RipacolaStandaloneSetup extends RipacolaStandaloneSetupGenerated {

	def static void doSetup() {
		new RipacolaStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
