/*
 * generated by Xtext 2.17.1
 */
package org.ripacola.lang.scoping


/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
class RipacolaScopeProvider extends AbstractRipacolaScopeProvider {

}
